config/routes.rb
Rails.application.routes.draw do
  resources :books

  resources :authors

  resources :publishers

  root 'books#index'

end

app/models/author.rb
class Author < ActiveRecord::Base
	has_many	:books
	validates 	:name, 		presence: true, length: { minimum: 1, maximum: 50 }
	validates 	:email,		presence: true, length: { maximum: 50 }
	validates 	:phone,		presence: true, length: { maximum: 15 }
	validates 	:address,	presence: true, length: { maximum: 100 }
end

app/models/book.rb
class Book < ActiveRecord::Base
	belongs_to	:author
	belongs_to	:publisher
	validates 	:name, 				presence: true, length: { minimum: 1, maximum: 50 }
	validates 	:description,		presence: true, length: { maximum: 100 }
	validates 	:price,				presence: true, length: { maximum: 5 }
	validates 	:published_date,	presence: true
	validates 	:author_id,			presence: true
	validate 	:validate_author_id
	validates 	:publisher_id,		presence: true
	validate 	:validate_publisher_id

	private

	  def validate_author_id
	    errors.add( :author_id, 'not found' ) unless Author.exists? ( self.author_id )
	  end
	  def validate_publisher_id
	    errors.add( :publisher_id, 'not found' ) unless Publisher.exists? ( self.publisher_id )
	  end
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
	has_many	:books
	validates 	:name, 		presence: true, length: { minimum: 1, maximum: 50 }
	validates 	:email,		presence: true, length: { maximum: 50 }
	validates 	:phone,		presence: true, length: { maximum: 15 }
	validates 	:address,	presence: true, length: { maximum: 100 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  before_action :set_author, only: [:show, :edit, :update, :destroy]

  def index
    @authors = Author.all
  end

  def show
  end

  def new
    @author = Author.new
  end

  def edit
  end

  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author has been successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author has been updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author has been deleted.' }
      format.json { head :no_content }
    end
  end

  private

    def set_author
      @author = Author.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        render 'record_not_found'
    end

    def author_params
      params.require(:author).permit(:name, :email, :phone, :address)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  def index
    @books = Book.all
  end

  def show
  end

  def new
    @book = Book.new
  end

  def edit
  end

  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book has been successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book has been updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book has been deleted.' }
      format.json { head :no_content }
    end
  end

  private

    def set_book
      @book = Book.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        render 'record_not_found'
    end

    def book_params
      params.require(:book).permit(:name, :description, :price, :published_date, :author_id, :publisher_id)
    end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  before_action :set_publisher, only: [:show, :edit, :update, :destroy]

  def index
    @publishers = Publisher.all
  end

  def show
  end

  def new
    @publisher = Publisher.new
  end

  def edit
  end

  def create
    @publisher = Publisher.new(publisher_params)

    respond_to do |format|
      if @publisher.save
        format.html { redirect_to @publisher, notice: 'Publisher has been successfully created.' }
        format.json { render :show, status: :created, location: @publisher }
      else
        format.html { render :new }
        format.json { render json: @publisher.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @publisher.update(publisher_params)
        format.html { redirect_to @publisher, notice: 'Publisher has been updated.' }
        format.json { render :show, status: :ok, location: @publisher }
      else
        format.html { render :edit }
        format.json { render json: @publisher.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @publisher.destroy
    respond_to do |format|
      format.html { redirect_to publishers_url, notice: 'Publisher has been deleted.' }
      format.json { head :no_content }
    end
  end

  private

    def set_publisher
      @publisher = Publisher.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        render 'record_not_found'
    end

    def publisher_params
      params.require(:publisher).permit(:name, :email, :phone, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/application/record_not_found.html.erb
<p id="notice">Record you are trying to access is either deleted or doesn't exist.</p>
<%= link_to 'Back', books_path %>

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> occurred saving author:</h2>

      <ul>
      <% @author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="actions">
    <%= f.submit 'Save' %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<div class="detail_view">
<h1>Edit</h1>
<%= render 'form' %>
<%= link_to 'View', @author %> |
<%= link_to 'Back', authors_path %>
</div>

app/views/authors/index.html.erb
<h1>Authors</h1>
<%= link_to 'Create New', new_author_path %>
<br><br>
<table>
  <tbody>
    <% if @authors.present? %>
      <thead>
        <tr>
          <th>Id</th>
          <th>Name</th>
          <th>Email</th>
          <th>Phone</th>
          <th>Address</th>
          <th>Actions</th>
        </tr>
      </thead>
      <% @authors.each do |author| %>
        <tr class="<%= cycle( 'odd_list', 'even_list' )%>">
          <td><%= link_to author.id, author %></td>
          <td><%= link_to author.name, author %></td>
          <td><%= author.email %></td>
          <td><%= author.phone %></td>
          <td><%= author.address %></td>
          <td><%= link_to 'Edit', edit_author_path(author) %> | <%= link_to 'Delete', author, method: :delete, data: { confirm: 'Are you sure you want to delete author?' } %></td>
        </tr>
      <% end %>
    <% else %>
      <span class="no_records" >
        Oops, no authors have been added.
      </span>
    <% end %>
  </tbody>
</table>

app/views/authors/new.html.erb
<h1>New author</h1>

<%= render 'form' %>

<%= link_to 'Cancel', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>
<div class="detail_view">
<p>
  <strong>Id:</strong>
  <%= @author.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @author.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @author.phone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @author.address %>
</p>
<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Delete', @author, method: :delete, data: { confirm: 'Are you sure you want to delete?' } %> |
<%= link_to 'Back', authors_path %>
</div>

app/views/books/_form.html.erb
<%= form_for(@book) do |f| %>
  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> occurred saving book:</h2>

      <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :published_date %><br>
    <%= f.date_select :published_date %>
  </div>
  <div class="field">
    <%= f.label :author_id %><br>
    <%= f.text_field :author_id %>
  </div>
  <div class="field">
    <%= f.label :publisher_id %><br>
    <%= f.text_field :publisher_id %>
  </div>
  <div class="actions">
    <%= f.submit 'Save' %>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="detail_view">
<h1>Edit</h1>
<%= render 'form' %>
<%= link_to 'View', @book %> |
<%= link_to 'Back', books_path %>
</div>

app/views/books/index.html.erb
<h1>Books</h1>
<%= link_to 'Create New', new_book_path %>
<br><br>
<table>
  <tbody>
    <% if @books.present? %>
      <thead>
        <tr>
          <th>Id</th>
          <th>Name</th>
          <th>Description</th>
          <th>Price</th>
          <th>Published Date</th>
          <th>Author</th>
          <th>Publisher</th>
          <th>Actions</th>
        </tr>
      </thead>
      <% @books.each do |book| %>
        <tr>
          <td><%= link_to book.id, book %></td>
          <td><%= link_to book.name, book %></td>
          <td><%= book.description %></td>
          <td><%= book.price %></td>
          <td><%= book.published_date %></td>
          <td><%= link_to book.author.name, book.author %></td>
          <td><%= link_to book.publisher.name, book.publisher %></td>
          <td><%= link_to 'Edit', edit_book_path(book) %> | <%= link_to 'Delete', book, method: :delete, data: { confirm: 'Are you sure you want to delete book?' } %></td>
        </tr>
      <% end %>
    <% else %>
      <span class="no_records" >
        Oops, no books have been added.
      </span>
    <% end %>
  </tbody>
</table>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Cancel', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>
<div class="detail_view">
<p>
  <strong>Id:</strong>
  <%= @book.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @book.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @book.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @book.price %>
</p>

<p>
  <strong>Published date:</strong>
  <%= @book.published_date %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author.name %>
</p>

<p>
  <strong>Publisher:</strong>
  <%= @book.publisher.name %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Delete', @book, method: :delete, data: { confirm: 'Are you sure you want to delete?' } %> | <%= link_to 'Back', books_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Log</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<table>
	<tr class="menu_table">
		<td>
			<%= link_to 'Books', books_path %>
		</td>
		<td>
			<%= link_to 'Authors', authors_path %>
		</td>
		<td>
			<%= link_to 'Publishers', publishers_path %>
		</td>
	</tr>
</table>
<%= yield %>

</body>
</html>

app/views/publishers/_form.html.erb
<%= form_for(@publisher) do |f| %>
  <% if @publisher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@publisher.errors.count, "error") %> occured saving publisher:</h2>
      <ul>
      <% @publisher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="actions">
    <%= f.submit 'Save' %>
  </div>
<% end %>

app/views/publishers/edit.html.erb
<div class="detail_view">
<h1>Edit</h1>
<%= render 'form' %>
<%= link_to 'View', @publisher %> |
<%= link_to 'Back', publishers_path %>
</div>

app/views/publishers/index.html.erb
<h1>Publishers</h1>

<%= link_to 'Create New', new_publisher_path %>
<br><br>

<table>
  <tbody>
    <% if @publishers.present? %>
      <thead>
        <tr>
          <th>Id</th>
          <th>Name</th>
          <th>Email</th>
          <th>Phone</th>
          <th>Address</th>
          <th>Actions</th>
        </tr>
      </thead>
      <% @publishers.each do |publisher| %>
        <tr class="<%= cycle( 'odd_list', 'even_list' )%>">
          <td><%= link_to publisher.id, publisher %></td>
          <td><%= link_to publisher.name, publisher %></td>
          <td><%= publisher.email %></td>
          <td><%= publisher.phone %></td>
          <td><%= publisher.address %></td>
          <td><%= link_to 'Edit', edit_publisher_path(publisher) %> | <%= link_to 'Delete', publisher, method: :delete, data: { confirm: 'Are you sure ypu want to delete publisher?' } %></td>
        </tr>
      <% end %>
    <% else %>
      <span class="no_records" >
        Oops, no publishers have been added.
      </span>
    <% end %>
  </tbody>
</table>

app/views/publishers/new.html.erb
<h1>New publisher</h1>

<%= render 'form' %>

<%= link_to 'Cancel', publishers_path %>

app/views/publishers/show.html.erb
<p id="notice"><%= notice %></p>
<div class="detail_view">
<p>
  <strong>Id:</strong>
  <%= @publisher.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @publisher.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @publisher.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @publisher.phone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @publisher.address %>
</p>

<%= link_to 'Edit', edit_publisher_path(@publisher) %> |
<%= link_to 'Delete', @publisher, method: :delete, data: { confirm: 'Are you sure ypu want to delete publisher?' } %> |
<%= link_to 'Back', publishers_path %>
</div>